djangochat/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    path('', views.frontpage, name='frontpage'),
    path('signup/', views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(
        template_name='core/login.html'),
        name='login'),
]

djangochat/djangochat/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('rooms/', include('room.urls', namespace='rooms')),
    path('admin/', admin.site.urls),
]

djangochat/room/urls.py
from django.urls import path

from . import views

app_name = 'rooms'

urlpatterns = [
    path('', views.get_room_list, name='room_list'),
    path('<slug:room_slug>', views.get_room_detail, name='room_detail'),
]

djangochat/room/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class Room(models.Model):
    name = models.CharField(
        verbose_name='Название комнаты',
        help_text='Поле для имени комнаты',
        max_length=50,
        blank=False
    )
    slug = models.SlugField(unique=True)
    create_date = models.DateTimeField(auto_now_add=True, null=True)

    class Meta():
        ordering = ('-create_date',)
        verbose_name = 'Комната'
        verbose_name_plural = 'Комнаты'

    def get_absolute_url(self):
        return reverse('rooms:room_detail', kwargs={'room_slug': self.slug})

    def __str__(self):
        return self.name[:15]


class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages',
                             on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='messages',
                             on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',)

djangochat/core/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class SignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username',)

djangochat/core/views.py
from django.contrib.auth import login
from django.shortcuts import redirect, render

from .forms import SignUpForm


def frontpage(request):
    return render(request, 'core/frontpage.html')


def signup(request):
    form = SignUpForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        login(request, user)
        return redirect('core:frontpage')
    return render(request, 'core/signup.html', {'form': form})

djangochat/room/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render

from .models import Message, Room


@login_required
def get_room_list(request):
    room_list = Room.objects.all()
    return render(request, 'room/room_list.html', {'room_list': room_list})


@login_required
def get_room_detail(request, room_slug):
    room = get_object_or_404(Room, slug=room_slug)
    messages = Message.objects.filter(room=room)[0:25]
    return render(request, 'room/room.html', {'room': room,
                                              'messages': messages})

djangochat/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}Djangochat</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="icon" type="image/png" sizes="96x96"
        href="{% static 'img/fav/icons-96.png' %}">
  <link rel="icon" type="image/png" sizes="192x192"
        href="{% static 'img/fav/icons8-chrome-192.png' %}">
  <link rel="apple-touch-icon" type="image/png" sizes="180x180"
        href="{% static 'img/fav/icons8-apple-180.png' %}">
</head>
<body class="bg-teal-600">
  <nav class="flex items-center justify-between px-4 py-6 bg-teal-800">
    <div>
      <a href="{% url 'core:frontpage' %}"
         class="text-xl text-white">Djangochat</a>
    </div>
    {% with request.resolver_match.view_name as view_name %}
    <div class="flex items-center space-x-4">
      {% if request.user.is_authenticated %}
        <a href="{% url 'core:room' %}"
           class="text-white hover:text-gray-200
            {% if view_name == 'core:room' %}
              px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700
                {% endif %}">Rooms</a>
        <a href="{% url 'core:logout' %}"
           class="text-white hover:text-gray-200
            {% if view_name == 'core:logout' %}
              px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700
                {% endif %}" >Logout</a>
      {% else %}
        <a href="{% url 'core:login' %}"
           class="text-white hover:text-gray-200
            {% if view_name == 'core:login' %}
              px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700
                {% endif %}">Log in</a>
        <a href="{% url 'core:signup' %}"
           class="text-white hover:text-gray-200
            {% if view_name == 'core:signup' %}
              px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700
                {% endif %}">Sign up</a>
      {% endif %}
    </div>
    {% endwith %}
  </nav>
  {% block content %}
  {% endblock %}
</body>
</html>

djangochat/core/templates/core/login.html
{% extends "core/base.html" %}
{% load user_filter %}

{% block title %}Login | {% endblock %}
{% block content %}
<div class="p-10 lg:p-20 text-center">
  <h1 class="text-3xl lg:text-6xl text-white">Log in</h1>
</div>

<form method="post" action="." class="lg:w-1/4 px-4 mx-auto">
  {% for error in form.non_field_errors %}
  <div class="px-5 py-3 rounded-xl text-white bg-teal-800 hover:bg-teal-700">
    <p>{{ error|escape }}</p>
  </div>
  {% endfor %}
  {% csrf_token %}
  {% for field in form %}
    <div class="mb-5">
      {{field.errors}}
      <label for="{{field.id_for_label}}" class="text-white">
        {{field.label}}
      </label>
      {{field|addclass:"w-full mt-2 px-4 -py-2 rounded-xl"}}
    </div>
  {% endfor %}
  <button class="px-5 py-3 rounded-xl text-white bg-teal-800 hover:bg-teal-700">
    Login</button>
</form>
{% endblock %}

djangochat/templates/core/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}Djangochat</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="icon" type="image/png" sizes="96x96"
        href="{% static 'img/fav/icons-96.png' %}">
  <link rel="icon" type="image/png" sizes="192x192"
        href="{% static 'img/fav/icons8-chrome-192.png' %}">
  <link rel="apple-touch-icon" type="image/png" sizes="180x180"
        href="{% static 'img/fav/icons8-apple-180.png' %}">
</head>
<body class="bg-teal-600">
  {% include 'includes/headers.html' %}
  {% block content %}
  {% endblock %}
  {% block scripts %}
  {% endblock %}
</body>
</html>

djangochat/templates/core/frontpage.html
{% extends "core/base.html" %}
{% block title %}Welcome | {% endblock %}
{% block content %}
<div class="p-10 lg:p-20 text-center">
  <h1 class="text-3xl lg:text-6xl text-white">Djangochat</h1>
</div>
{% endblock %}

djangochat/templates/core/login.html
{% extends "core/base.html" %}
{% load user_filter %}

{% block title %}Login | {% endblock %}
{% block content %}
<div class="p-10 lg:p-20 text-center">
  <h1 class="text-3xl lg:text-6xl text-white">Log in</h1>
</div>

<form method="post" action="." class="lg:w-1/4 px-4 mx-auto">
  {% csrf_token %}
  {% for error in form.non_field_errors %}
  <div class="px-5 py-3 rounded-xl text-white bg-teal-800 hover:bg-teal-700">
    <p>{{ error|escape }}</p>
  </div>
  {% endfor %}
  {% for field in form %}
    <div class="mb-5">
      {{field.errors}}
      <label for="{{field.id_for_label}}" class="text-white">
        {{field.label}}
      </label>
      {{field|addclass:"w-full mt-2 px-4 -py-2 rounded-xl"}}
    </div>
  {% endfor %}
  <button class="px-5 py-3 rounded-xl text-white bg-teal-800 hover:bg-teal-700">
    Login</button>
</form>
{% endblock %}

djangochat/templates/core/signup.html
{% extends "core/base.html" %}
{% block title %}Sign up | {% endblock %}
{% block content %}

<div class="p-10 lg:p-20 text-center">
  <h1 class="text-3xl lg:text-6xl text-white">Sign up</h1>
</div>
<form method="post" action="." class="lg:w-1/4 px-4 mx-auto">
  {% csrf_token %}
  <div class="mb-5">
    <label class="text-white">Username</label>
    <input type="text" name="username" class="w-full mt-2 px-4 -py-2 rounded-xl">
  </div>

  <div class="mb-5">
    <label class="text-white">Password</label>
    <input type="password" name="password1" class="w-full mt-2 px-4 -py-2 rounded-xl">
  </div>

  <div class="mb-5">
    <label class="text-white">Confirm password</label>
    <input type="password" name="password2" class="w-full mt-2 px-4 -py-2 rounded-xl">
  </div>
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
          <p>{{ error|escape }}</p>
        </div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  <button class="px-5 py-3 rounded-xl text-white bg-teal-800
    hover:bg-teal-700">Submit</button>
</form>
{% endblock %}

djangochat/templates/includes/headers.html
<nav class="flex items-center justify-between px-4 py-6 bg-teal-800">
  <div>
    <a href="{% url 'core:frontpage' %}"
       class="text-xl text-white">Djangochat</a>
  </div>
  {% with request.resolver_match.view_name as view_name %}
  <div class="flex items-center space-x-4">
    {% if request.user.is_authenticated %}
      <a href="{% url 'rooms:room_list' %}"
         class="text-white hover:text-gray-200
          {% if view_name == 'rooms:room_list' or 'rooms:room_detail' %}
            px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700
              {% endif %}">Rooms</a>
      <a href="{% url 'core:logout' %}"
         class="text-white hover:text-gray-200
          {% if view_name == 'core:logout' %}
            px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700
              {% endif %}" >Logout</a>
    {% else %}
      <a href="{% url 'core:login' %}"
         class="text-white hover:text-gray-200
          {% if view_name == 'core:login' %}
            px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700
              {% endif %}">Log in</a>
      <a href="{% url 'core:signup' %}"
         class="text-white hover:text-gray-200
          {% if view_name == 'core:signup' %}
            px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700
              {% endif %}">Sign up</a>
    {% endif %}
  </div>
  {% endwith %}
</nav>

djangochat/templates/room/room.html
{% extends 'core/base.html' %}

{% block title %}{{ room.name }} | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">{{ room.name }}</h1>
</div>

<div class="lg:w-2/4 mx-4 lg:mx-auto p-4 bg-white rounded-xl">
    <div class="chat-messages space-y-3" id="chat-messages">
        {% for message in messages %}
            <div class="p-4 bg-gray-200 rounded-xl">
                <p class="font-semibold">{{ message.user.username }}</p>
                <p>{{ message.content }}</p>
            </div>
        {% endfor %}
    </div>
</div>

<div class="lg:w-2/4 mt-6 mx-4 lg:mx-auto p-4 bg-white rounded-xl">
    <form method="post" action="." class="flex">
        <input type="text" name="content" class="flex-1 mr-3"
               placeholder="Your message..." id="chat-message-input">

        <button
            class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700"
            id="chat-message-submit"
        >Submit</button>
    </form>
</div>
{% endblock %}

{% block scripts %}
{{ room.slug|json_script:"json-roomname" }}
{{ request.user.username|json_script:"json-username" }}

<script>
    const roomName = JSON.parse(document.getElementById('json-roomname').textContent);
    const userName = JSON.parse(document.getElementById('json-username').textContent);


    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/'
        + roomName
        + '/'
    );

    chatSocket.onmessage = function(e) {
        console.log('onmessage')

        const data = JSON.parse(e.data);

        if (data.message) {
            let html = '<div class="p-4 bg-gray-200 rounded-xl">';
                html += '<p class="font-semibold">' + data.username + '</p>';
                html += '<p>' + data.message + '</p></div>';

            document.querySelector('#chat-messages').innerHTML += html;

            scrollToBottom();
        }
        else {
            alert('The message was empty!');
        }
    }

    chatSocket.onclose = function(e) {
        console.log('onclose')
    }

    //

    document.querySelector('#chat-message-submit').onclick = function(e) {
        e.preventDefault()

        console.log('submit')
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;

        chatSocket.send(JSON.stringify({
            'message': message,
            'username': userName,
            'room': roomName,
        }));

        messageInputDom.value = '';

        return false;
    }

    //

    function scrollToBottom() {
        const objDiv = document.querySelector('#chat-messages');
        objDiv.scrollTop = objDiv.scrollHeight;
    }

    scrollToBottom();
</script>
{% endblock %}

djangochat/templates/room/room_list.html
{% extends 'core/base.html' %}

{% block title %}Rooms | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">Rooms</h1>
</div>

<div class="w-full flex flex-wrap items-center">
    {% for room in room_list %}
        <div class="w-full lg:w-1/4 px-3 py-3">
            <div class="p-4 bg-white shadow rounded-xl text-center">
                <h2 class="mb-5 text-2xl font-semibold">{{ room.name }}</h2>
                <a href="{{ room.get_absolute_url}}"
                   class="px-5 py-3 block rounded-xl text-white
                    bg-teal-600 hover:bg-teal-700">Join</a>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}